/**
 * VISTA MEDICAL SYSTEMS — Theme Configuration
 * ─────────────────────────────────────
 * Each role gets its own blue-family shade.
 * To change a palette, edit ONLY this file.
 *
 * Roles:
 *   doctor      — deep royal blue
 *   admin       — slate-indigo blue
 *   patient     — soft teal-blue
 *   birthRecord — midnight navy blue
 */

export const ROLE_THEMES = {
  doctor: {
    name: 'doctor',
    label: 'Doctor',
    light: {
      '--pm-primary':        '#1a56db',
      '--pm-primary-dark':   '#1e429f',
      '--pm-primary-light':  '#e8f0fe',
      '--pm-primary-muted':  '#93a8f4',
      '--pm-accent':         '#0ea5e9',
      '--pm-bg':             '#f0f4ff',
      '--pm-surface':        '#ffffff',
      '--pm-surface-2':      '#f8faff',
      '--pm-border':         '#dde3f4',
      '--pm-text':           '#111827',
      '--pm-text-muted':     '#6b7280',
      '--pm-sidebar-bg':     '#0f2d6b',
      '--pm-sidebar-text':   '#c7d8ff',
      '--pm-sidebar-active': '#1a56db',
      '--pm-success':        '#16a34a',
      '--pm-warning':        '#d97706',
      '--pm-danger':         '#dc2626',
      '--pm-info':           '#0284c7',
    },
    dark: {
      '--pm-primary':        '#3b7af8',
      '--pm-primary-dark':   '#1e429f',
      '--pm-primary-light':  '#1e2f55',
      '--pm-primary-muted':  '#4b6cb7',
      '--pm-accent':         '#38bdf8',
      '--pm-bg':             '#0a0f1e',
      '--pm-surface':        '#111827',
      '--pm-surface-2':      '#1c2336',
      '--pm-border':         '#2a3550',
      '--pm-text':           '#f1f5f9',
      '--pm-text-muted':     '#94a3b8',
      '--pm-sidebar-bg':     '#070d1a',
      '--pm-sidebar-text':   '#94b4e8',
      '--pm-sidebar-active': '#3b7af8',
      '--pm-success':        '#22c55e',
      '--pm-warning':        '#f59e0b',
      '--pm-danger':         '#ef4444',
      '--pm-info':           '#38bdf8',
    },
  },

  admin: {
    name: 'admin',
    label: 'Admin',
    light: {
      '--pm-primary':        '#4338ca',
      '--pm-primary-dark':   '#312e81',
      '--pm-primary-light':  '#ede9fe',
      '--pm-primary-muted':  '#a5b4fc',
      '--pm-accent':         '#6366f1',
      '--pm-bg':             '#f2f0ff',
      '--pm-surface':        '#ffffff',
      '--pm-surface-2':      '#f9f8ff',
      '--pm-border':         '#e0ddf7',
      '--pm-text':           '#111827',
      '--pm-text-muted':     '#6b7280',
      '--pm-sidebar-bg':     '#1e1b4b',
      '--pm-sidebar-text':   '#c4b5fd',
      '--pm-sidebar-active': '#4338ca',
      '--pm-success':        '#16a34a',
      '--pm-warning':        '#d97706',
      '--pm-danger':         '#dc2626',
      '--pm-info':           '#0284c7',
    },
    dark: {
      '--pm-primary':        '#6366f1',
      '--pm-primary-dark':   '#4338ca',
      '--pm-primary-light':  '#1e1c3a',
      '--pm-primary-muted':  '#4f46a0',
      '--pm-accent':         '#818cf8',
      '--pm-bg':             '#0c0b1a',
      '--pm-surface':        '#14122a',
      '--pm-surface-2':      '#1e1c36',
      '--pm-border':         '#2d2b50',
      '--pm-text':           '#f1f5f9',
      '--pm-text-muted':     '#94a3b8',
      '--pm-sidebar-bg':     '#080714',
      '--pm-sidebar-text':   '#a5b4fc',
      '--pm-sidebar-active': '#6366f1',
      '--pm-success':        '#22c55e',
      '--pm-warning':        '#f59e0b',
      '--pm-danger':         '#ef4444',
      '--pm-info':           '#38bdf8',
    },
  },

  patient: {
    name: 'patient',
    label: 'Patient',
    light: {
      '--pm-primary':        '#0891b2',
      '--pm-primary-dark':   '#0e7490',
      '--pm-primary-light':  '#ecfeff',
      '--pm-primary-muted':  '#67e8f9',
      '--pm-accent':         '#06b6d4',
      '--pm-bg':             '#f0faff',
      '--pm-surface':        '#ffffff',
      '--pm-surface-2':      '#f8fdff',
      '--pm-border':         '#cdf0f7',
      '--pm-text':           '#111827',
      '--pm-text-muted':     '#6b7280',
      '--pm-sidebar-bg':     '#0c4a6e',
      '--pm-sidebar-text':   '#a5e0f5',
      '--pm-sidebar-active': '#0891b2',
      '--pm-success':        '#16a34a',
      '--pm-warning':        '#d97706',
      '--pm-danger':         '#dc2626',
      '--pm-info':           '#0284c7',
    },
    dark: {
      '--pm-primary':        '#22d3ee',
      '--pm-primary-dark':   '#0891b2',
      '--pm-primary-light':  '#0f2d38',
      '--pm-primary-muted':  '#1e7a8a',
      '--pm-accent':         '#67e8f9',
      '--pm-bg':             '#080f14',
      '--pm-surface':        '#0f1e26',
      '--pm-surface-2':      '#162a36',
      '--pm-border':         '#1e3d4f',
      '--pm-text':           '#f1f5f9',
      '--pm-text-muted':     '#94a3b8',
      '--pm-sidebar-bg':     '#050d12',
      '--pm-sidebar-text':   '#67e8f9',
      '--pm-sidebar-active': '#22d3ee',
      '--pm-success':        '#22c55e',
      '--pm-warning':        '#f59e0b',
      '--pm-danger':         '#ef4444',
      '--pm-info':           '#38bdf8',
    },
  },

  birthRecord: {
    name: 'birthRecord',
    label: 'Birth Records Admin',
    light: {
      '--pm-primary':        '#1e3a8a',
      '--pm-primary-dark':   '#172554',
      '--pm-primary-light':  '#dbeafe',
      '--pm-primary-muted':  '#93c5fd',
      '--pm-accent':         '#2563eb',
      '--pm-bg':             '#eef3ff',
      '--pm-surface':        '#ffffff',
      '--pm-surface-2':      '#f8faff',
      '--pm-border':         '#d1ddf9',
      '--pm-text':           '#111827',
      '--pm-text-muted':     '#6b7280',
      '--pm-sidebar-bg':     '#0f1f4a',
      '--pm-sidebar-text':   '#bfcfef',
      '--pm-sidebar-active': '#1e3a8a',
      '--pm-success':        '#16a34a',
      '--pm-warning':        '#d97706',
      '--pm-danger':         '#dc2626',
      '--pm-info':           '#0284c7',
    },
    dark: {
      '--pm-primary':        '#3b82f6',
      '--pm-primary-dark':   '#1d4ed8',
      '--pm-primary-light':  '#172038',
      '--pm-primary-muted':  '#2d5098',
      '--pm-accent':         '#60a5fa',
      '--pm-bg':             '#070b18',
      '--pm-surface':        '#0f1628',
      '--pm-surface-2':      '#172038',
      '--pm-border':         '#1e2f52',
      '--pm-text':           '#f1f5f9',
      '--pm-text-muted':     '#94a3b8',
      '--pm-sidebar-bg':     '#04080f',
      '--pm-sidebar-text':   '#93c5fd',
      '--pm-sidebar-active': '#3b82f6',
      '--pm-success':        '#22c55e',
      '--pm-warning':        '#f59e0b',
      '--pm-danger':         '#ef4444',
      '--pm-info':           '#38bdf8',
    },
  },
};

export const USERS = [
  {
    id: 'doctor',
    role: 'doctor',
    name: 'Dr. Sarah Mpande',
    title: 'Senior Obstetrician',
    email: 'sarah.mpande@pari.health',
    password: 'doctor123',
    avatar: null,
  },
  {
    id: 'admin',
    role: 'admin',
    name: 'Grace Mugwagwa',
    title: 'Hospital Administrator',
    email: 'grace.mugwagwa@pari.health',
    password: 'admin123',
    avatar: null,
  },
  {
    id: 'patient',
    role: 'patient',
    name: 'Amara Ngwendeza',
    title: 'Patient — Week 24',
    email: 'amara.ngwendeza@email.com',
    password: 'patient123',
    avatar: null,
  },
  {
    id: 'birthRecord',
    role: 'birthRecord',
    name: 'Jabu Khumalo',
    title: 'Birth Records Administrator',
    email: 'jabu.khumalo@pari.health',
    password: 'birth123',
    avatar: null,
  },
];
