import React, { useMemo, useState } from 'react';
import { Receipt, Plus, Eye, CreditCard, Printer, WalletCards } from 'lucide-react';
import { PageHeader, MetricCard, StatusBadge, SearchFilter, Modal, FormField, DetailGrid, DetailItem, Toast, EmptyState, money } from '../../components/AdminOperationsUI';

const INITIAL=[
 {id:'INV-260905-018',patient:'Tendai Muchengeti',patientId:'PT-10482',date:'05 Sep 2026',department:'General Medicine',payer:'CIMAS Medical Aid',total:286.50,paid:120,status:'Partial',lines:[['Consultation','General physician review',35,1],['Medication','Amlodipine 10mg · 14 tablets',8.5,1],['Laboratory','FBC + U&E + Troponin',63,1],['Accommodation','Medical Ward A · 1 night',180,1]],payments:[['05 Sep 2026 · 08:12','EcoCash',120,'EC-4912081']]},
 {id:'INV-260905-014',patient:'Rutendo Shoko',patientId:'PT-10217',date:'05 Sep 2026',department:'Emergency Room',payer:'Self-pay',total:94,paid:0,status:'Unpaid',lines:[['Emergency','ER facility fee',40,1],['Procedure','Wound cleaning & suturing',36,1],['Medication','Tetanus toxoid + analgesia',18,1]],payments:[]},
 {id:'INV-260904-041',patient:'Chipo Dube',patientId:'PT-07631',date:'04 Sep 2026',department:'Endoscopy',payer:'BonVie Medical Aid',total:212,paid:212,status:'Paid',lines:[['Procedure','Upper GI endoscopy',165,1],['Medication','Sedation medicines',27,1],['Consumables','Endoscopy disposables',20,1]],payments:[['04 Sep 2026 · 15:44','Medical Aid',162,'BV-CLAIM-8831'],['04 Sep 2026 · 15:47','Swipe / POS',50,'POS-208194']]},
];
const methods=['Cash','EcoCash','OneMoney','InnBucks','Swipe / POS','Bank Transfer','Medical Aid','Insurance Claim'];
const empty={patient:'',patientId:'',department:'General Medicine',payer:'Self-pay',description:'Consultation',category:'Consultation',amount:'35'};

export default function BillingManagementPage(){
 const [invoices,setInvoices]=useState(INITIAL),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(null),[showNew,setShowNew]=useState(false),[showPay,setShowPay]=useState(false),[form,setForm]=useState(empty),[payment,setPayment]=useState({amount:'',method:'EcoCash',reference:''}),[toast,setToast]=useState('');
 const filtered=useMemo(()=>invoices.filter(i=>{const q=search.toLowerCase();return (!q||[i.id,i.patient,i.patientId,i.department,i.payer].join(' ').toLowerCase().includes(q))&&(filter==='All'||i.status===filter)}),[invoices,search,filter]);
 const total=invoices.reduce((s,i)=>s+i.total,0),paid=invoices.reduce((s,i)=>s+i.paid,0),owed=total-paid;
 const createInvoice=()=>{if(!form.patient.trim()||!Number(form.amount))return;const amount=Number(form.amount);const next={id:`INV-260905-${String(invoices.length+19).padStart(3,'0')}`,patient:form.patient,patientId:form.patientId||`PT-${11200+invoices.length}`,date:'05 Sep 2026',department:form.department,payer:form.payer,total:amount,paid:0,status:'Unpaid',lines:[[form.category,form.description,amount,1]],payments:[]};setInvoices([next,...invoices]);setShowNew(false);setForm(empty);setToast(`${next.id} created for ${next.patient}`)};
 const openPayment=(inv)=>{setSelected(inv);setPayment({amount:String(Math.max(0,inv.total-inv.paid).toFixed(2)),method:'EcoCash',reference:''});setShowPay(true)};
 const takePayment=()=>{if(!selected)return;const amt=Math.min(Number(payment.amount||0),selected.total-selected.paid);if(amt<=0)return;const newPaid=selected.paid+amt;const next={...selected,paid:newPaid,status:newPaid>=selected.total?'Paid':'Partial',payments:[[ '05 Sep 2026 · now',payment.method,amt,payment.reference||'Pending reference'],...selected.payments]};setInvoices(xs=>xs.map(x=>x.id===selected.id?next:x));setSelected(next);setShowPay(false);setToast(`${money(amt)} payment posted to ${selected.id}`)};
 return <>
  <PageHeader icon="Receipt" title="Patient Billing" subtitle="Manage itemised invoices, patient balances, medical aid claims and Zimbabwe payment channels." actions={<><button className="pm-btn pm-btn-outline"><Printer size={15}/> Daily billing report</button><button className="pm-btn pm-btn-primary" onClick={()=>setShowNew(true)}><Plus size={15}/> New invoice</button></>}/>
  <div className="ops-metrics"><MetricCard icon="Receipt" label="Billed" value={money(total)} note="Current invoice register"/><MetricCard icon="CircleDollarSign" label="Collected" value={money(paid)} note={`${Math.round((paid/total)*100)}% collection rate`} tone="success"/><MetricCard icon="Clock3" label="Outstanding" value={money(owed)} note="Patient / payer balances" tone="warning"/><MetricCard icon="WalletCards" label="Open invoices" value={invoices.filter(i=>i.status!=='Paid').length} note="Requires settlement" tone="info"/></div>
  <div className="ops-workspace"><SearchFilter search={search} onSearch={setSearch} placeholder="Search invoice, patient, department or payer…"><select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Unpaid','Partial','Paid'].map(x=><option key={x}>{x}</option>)}</select></SearchFilter><div className="ops-table-wrap">{filtered.length?<table className="ops-table"><thead><tr><th>Invoice</th><th>Patient</th><th>Department</th><th>Payer</th><th>Total</th><th>Paid / Balance</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(i=><tr key={i.id} onClick={()=>setSelected(i)}><td><div className="ops-cell-primary">{i.id}</div><div className="ops-cell-sub">{i.date}</div></td><td><div className="ops-cell-primary">{i.patient}</div><div className="ops-cell-sub">{i.patientId}</div></td><td>{i.department}</td><td>{i.payer}</td><td><strong>{money(i.total)}</strong></td><td><div className="ops-cell-primary ops-success-text">{money(i.paid)}</div><div className="ops-cell-sub">Balance {money(i.total-i.paid)}</div></td><td><StatusBadge status={i.status}/></td><td><div className="ops-row-actions"><button className="ops-icon-button" onClick={e=>{e.stopPropagation();setSelected(i)}}><Eye size={15}/></button>{i.status!=='Paid'&&<button className="ops-icon-button" onClick={e=>{e.stopPropagation();openPayment(i)}}><CreditCard size={15}/></button>}</div></td></tr>)}</tbody></table>:<EmptyState icon="Receipt" title="No invoices found"/>}</div></div>
  <Modal open={showNew} onClose={()=>setShowNew(false)} title="Create patient invoice" subtitle="Start an itemised charge for a clinical service, medicine, procedure or accommodation." icon="Receipt" size="lg" footer={<><button className="pm-btn pm-btn-ghost" onClick={()=>setShowNew(false)}>Cancel</button><button className="pm-btn pm-btn-primary" onClick={createInvoice}>Create invoice</button></>}><div className="ops-form-grid"><FormField label="Patient name"><input value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}/></FormField><FormField label="Patient ID"><input value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})} placeholder="PT-xxxxx"/></FormField><FormField label="Department"><select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}><option>General Medicine</option><option>Emergency Room</option><option>Pharmacy</option><option>Laboratory</option><option>Radiology</option><option>General Surgery</option></select></FormField><FormField label="Payer"><select value={form.payer} onChange={e=>setForm({...form,payer:e.target.value})}><option>Self-pay</option><option>CIMAS Medical Aid</option><option>PSMAS</option><option>First Mutual Health</option><option>BonVie Medical Aid</option><option>Corporate account</option></select></FormField><FormField label="Charge category"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Consultation</option><option>Medication</option><option>Laboratory</option><option>Radiology</option><option>Procedure</option><option>Accommodation</option><option>Consumables</option></select></FormField><FormField label="Amount (USD)"><input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></FormField><label className="ops-field wide"><span>Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div></Modal>
  <Modal open={!!selected&&!showPay} onClose={()=>setSelected(null)} title={selected?.id||''} subtitle={selected?`${selected.patient} · ${selected.patientId}`:''} icon="Receipt" size="lg" footer={selected&&selected.status!=='Paid'?<><button className="pm-btn pm-btn-outline"><Printer size={14}/> Print invoice</button><button className="pm-btn pm-btn-primary" onClick={()=>openPayment(selected)}><CreditCard size={14}/> Record payment</button></>:<button className="pm-btn pm-btn-ghost" onClick={()=>setSelected(null)}>Close</button>}>
   {selected&&<><DetailGrid><DetailItem label="Invoice status" value={<StatusBadge status={selected.status}/>}/><DetailItem label="Payer" value={selected.payer}/><DetailItem label="Department" value={selected.department}/><DetailItem label="Invoice date" value={selected.date}/></DetailGrid><div className="ops-section"><div className="ops-section-title"><h4>Itemised charges</h4></div><div className="ops-list"><table className="ops-invoice-lines"><thead><tr><th>Category</th><th>Description</th><th>Qty</th><th style={{textAlign:'right'}}>Amount</th></tr></thead><tbody>{selected.lines.map((l,n)=><tr key={n}><td>{l[0]}</td><td><strong>{l[1]}</strong></td><td>{l[3]}</td><td style={{textAlign:'right'}}>{money(l[2]*l[3])}</td></tr>)}</tbody></table></div><div className="ops-summary-strip"><div className="ops-summary-box"><span>Invoice total</span><strong>{money(selected.total)}</strong></div><div className="ops-summary-box"><span>Paid</span><strong className="ops-success-text">{money(selected.paid)}</strong></div><div className="ops-summary-box"><span>Balance due</span><strong className={selected.total-selected.paid>0?'ops-danger-text':''}>{money(selected.total-selected.paid)}</strong></div></div></div><div className="ops-section"><div className="ops-section-title"><h4>Payment transactions</h4></div>{selected.payments.length?<div className="ops-list">{selected.payments.map((p,n)=><div className="ops-list-row" key={n}><div><strong>{p[1]}</strong><small>{p[0]} · Ref {p[3]}</small></div><strong>{money(p[2])}</strong></div>)}</div>:<div className="ops-callout"><WalletCards size={18}/><div><strong>No payment transactions yet</strong><span>The full balance remains outstanding.</span></div></div>}</div></>}
  </Modal>
  <Modal open={showPay} onClose={()=>setShowPay(false)} title="Record payment" subtitle={selected?`${selected.id} · balance ${money(selected.total-selected.paid)}`:''} icon="CreditCard" size="sm" footer={<><button className="pm-btn pm-btn-ghost" onClick={()=>setShowPay(false)}>Cancel</button><button className="pm-btn pm-btn-primary" onClick={takePayment}>Post payment</button></>}><div className="ops-form-grid"><FormField label="Amount (USD)"><input type="number" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></FormField><FormField label="Payment method"><select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}>{methods.map(x=><option key={x}>{x}</option>)}</select></FormField><label className="ops-field wide"><span>Transaction / claim reference</span><input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})} placeholder="EcoCash reference, POS receipt, bank reference or claim number"/></label></div></Modal>
  <Toast message={toast} onClose={()=>setToast('')}/>
 </>;
}
