import React, { useMemo, useState } from 'react';
import { Ticket, Plus, Megaphone, Stethoscope, CheckCircle2, Eye } from 'lucide-react';
import { PageHeader, MetricCard, StatusBadge, SearchFilter, Modal, FormField, DetailGrid, DetailItem, Toast, EmptyState } from '../../components/AdminOperationsUI';

const INITIAL=[
 {ticket:'A-041',patient:'Nyasha Moyo',patientId:'PT-10920',service:'General Consultation',priority:'Standard',doctor:'Dr. R. Moyo',issued:'07:16',wait:35,status:'Waiting',room:'Consult 4',reason:'Persistent headache'},
 {ticket:'A-042',patient:'Memory Dube',patientId:'PT-10927',service:'General Consultation',priority:'Priority',doctor:'Dr. B. Mlambo',issued:'07:27',wait:24,status:'Waiting',room:'Consult 2',reason:'Asthma review'},
 {ticket:'B-018',patient:'Tatenda Zhou',patientId:'PT-10663',service:'Surgical Review',priority:'Standard',doctor:'Dr. T. Chirwa',issued:'07:34',wait:17,status:'In consultation',room:'Consult 6',reason:'Post-op wound review'},
 {ticket:'P-009',patient:'Rufaro Ncube',patientId:'PT-10192',service:'Paediatrics',priority:'Priority',doctor:'Dr. L. Hove',issued:'07:39',wait:12,status:'Waiting',room:'Paeds 1',reason:'Fever and cough'},
 {ticket:'A-039',patient:'Farai Ndlovu',patientId:'PT-10711',service:'General Consultation',priority:'Standard',doctor:'Dr. R. Moyo',issued:'07:02',wait:0,status:'Completed',room:'Consult 4',reason:'Hypertension follow-up'},
];
const empty={patient:'',patientId:'',service:'General Consultation',priority:'Standard',doctor:'Dr. R. Moyo',room:'Consult 4',reason:''};

export default function QueueManagementPage(){
 const [tickets,setTickets]=useState(INITIAL),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(null),[showNew,setShowNew]=useState(false),[form,setForm]=useState(empty),[toast,setToast]=useState('');
 const filtered=useMemo(()=>tickets.filter(t=>{const q=search.toLowerCase();return(!q||[t.ticket,t.patient,t.patientId,t.service,t.doctor,t.room].join(' ').toLowerCase().includes(q))&&(filter==='All'||t.service===filter||t.status===filter)}),[tickets,search,filter]);
 const patch=(t,patch,msg)=>{const next={...t,...patch};setTickets(xs=>xs.map(x=>x.ticket===t.ticket?next:x));if(selected?.ticket===t.ticket)setSelected(next);if(msg)setToast(msg)};
 const issue=()=>{if(!form.patient.trim())return;const prefix=form.service==='Paediatrics'?'P':form.service==='Surgical Review'?'B':'A';const num=String(43+tickets.length).padStart(3,'0');const next={...form,ticket:`${prefix}-${num}`,patientId:form.patientId||`PT-${11300+tickets.length}`,issued:'now',wait:0,status:'Waiting'};setTickets([next,...tickets]);setShowNew(false);setForm(empty);setToast(`Ticket ${next.ticket} issued to ${next.patient}`)};
 const callNext=()=>{const waiting=tickets.filter(t=>t.status==='Waiting').sort((a,b)=>(b.priority==='Priority')-(a.priority==='Priority')||b.wait-a.wait)[0];if(waiting)patch(waiting,{status:'In consultation'},`${waiting.ticket} called to ${waiting.room}`)};
 return <>
  <PageHeader icon="Ticket" title="Consultation Queue" subtitle="Issue visit tickets, monitor waiting times, call patients and track consultations through completion." actions={<><button className="pm-btn pm-btn-outline" onClick={callNext}><Megaphone size={15}/> Call next patient</button><button className="pm-btn pm-btn-primary" onClick={()=>setShowNew(true)}><Plus size={15}/> Issue ticket</button></>}/>
  <div className="ops-metrics"><MetricCard icon="Users" label="Waiting" value={tickets.filter(t=>t.status==='Waiting').length} note="Across consultation services"/><MetricCard icon="Clock3" label="Longest wait" value={`${Math.max(...tickets.filter(t=>t.status==='Waiting').map(t=>t.wait),0)} min`} note="Current waiting list" tone="warning"/><MetricCard icon="Stethoscope" label="In consultation" value={tickets.filter(t=>t.status==='In consultation').length} note="Patients with clinicians" tone="info"/><MetricCard icon="CheckCircle2" label="Completed" value={tickets.filter(t=>t.status==='Completed').length} note="Consultations closed today" tone="success"/></div>
  <div className="ops-workspace"><SearchFilter search={search} onSearch={setSearch} placeholder="Search ticket, patient, service, doctor or room…"><select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Waiting','In consultation','Completed','General Consultation','Surgical Review','Paediatrics'].map(x=><option key={x}>{x}</option>)}</select></SearchFilter>
   <div className="ops-queue-grid">
    {['Waiting','In consultation','Completed'].map(col=><div className="ops-queue-column" key={col}><div className="ops-queue-column-head"><strong>{col}</strong><span className="pm-badge pm-badge-neutral">{filtered.filter(t=>t.status===col).length}</span></div>{filtered.filter(t=>t.status===col).map(t=><div className="ops-queue-card" key={t.ticket} onClick={()=>setSelected(t)}><div className="ops-queue-ticket"><strong>{t.ticket}</strong><StatusBadge status={t.priority==='Priority'?'Urgent':t.status}/></div><div className="ops-queue-name">{t.patient}</div><div className="ops-queue-meta">{t.service} · {t.doctor}</div><div className="ops-queue-meta">{t.room} · {col==='Waiting'?`${t.wait} min waiting`:`issued ${t.issued}`}</div>{col==='Waiting'&&<div className="ops-progress-line"><span style={{width:`${Math.min(100,t.wait*2)}%`}}/></div>}</div>)}{!filtered.some(t=>t.status===col)&&<EmptyState icon="Ticket" title={`No ${col.toLowerCase()} tickets`} text="This column is clear."/>}</div>)}
   </div>
  </div>
  <Modal open={showNew} onClose={()=>setShowNew(false)} title="Issue consultation ticket" subtitle="Add a patient to the correct clinical waiting queue." icon="Ticket" size="lg" footer={<><button className="pm-btn pm-btn-ghost" onClick={()=>setShowNew(false)}>Cancel</button><button className="pm-btn pm-btn-primary" onClick={issue}>Issue ticket</button></>}><div className="ops-form-grid"><FormField label="Patient name"><input value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}/></FormField><FormField label="Patient ID"><input value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}/></FormField><FormField label="Service"><select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option>General Consultation</option><option>Surgical Review</option><option>Paediatrics</option><option>Orthopaedics</option><option>Cardiology</option></select></FormField><FormField label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Standard</option><option>Priority</option></select></FormField><FormField label="Doctor"><select value={form.doctor} onChange={e=>setForm({...form,doctor:e.target.value})}><option>Dr. R. Moyo</option><option>Dr. B. Mlambo</option><option>Dr. T. Chirwa</option><option>Dr. L. Hove</option></select></FormField><FormField label="Room"><input value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/></FormField><label className="ops-field wide"><span>Reason for consultation</span><textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div></Modal>
  <Modal open={!!selected} onClose={()=>setSelected(null)} title={`${selected?.ticket||''} · ${selected?.patient||''}`} subtitle={selected?`${selected.service} · issued ${selected.issued}`:''} icon="Ticket" size="sm" footer={<button className="pm-btn pm-btn-ghost" onClick={()=>setSelected(null)}>Close</button>}>
   {selected&&<><DetailGrid><DetailItem label="Queue status" value={<StatusBadge status={selected.status}/>}/><DetailItem label="Priority" value={selected.priority}/><DetailItem label="Patient ID" value={selected.patientId}/><DetailItem label="Waiting time" value={`${selected.wait} minutes`}/><DetailItem label="Doctor" value={selected.doctor}/><DetailItem label="Room" value={selected.room}/><DetailItem label="Reason" value={selected.reason} wide/></DetailGrid><div className="ops-section"><div className="ops-section-title"><h4>Queue actions</h4></div><div className="ops-inline-actions"><button className="pm-btn pm-btn-outline" onClick={()=>patch(selected,{status:'In consultation'},`${selected.ticket} called to ${selected.room}`)}><Megaphone size={14}/> Call patient</button><button className="pm-btn pm-btn-outline" onClick={()=>patch(selected,{status:'In consultation'},'Consultation started')}><Stethoscope size={14}/> Start consultation</button><button className="pm-btn pm-btn-primary" onClick={()=>patch(selected,{status:'Completed',wait:0},`${selected.ticket} marked complete`)}><CheckCircle2 size={14}/> Complete</button></div></div></>}
  </Modal>
  <Toast message={toast} onClose={()=>setToast('')}/>
 </>;
}
