import React, { useMemo, useState } from 'react';
import {
  Calculator, Plus, Search, Eye, X, Banknote, TrendingDown, Landmark,
  FileText, CheckCircle2, Clock, Building2, Receipt, ArrowUpRight,
} from 'lucide-react';
import { createExpense, getFinanceData, money } from '../../data/billingStore';

const inputStyle = { width: '100%', padding: '10px 12px', border: '1px solid var(--pm-border)', borderRadius: 9, background: 'var(--pm-surface-2)', color: 'var(--pm-text)', fontSize: '0.82rem' };

function Modal({ title, subtitle, icon: Icon, onClose, children, footer }) {
  return <div style={{ position: 'fixed', inset: 0, zIndex: 1060, background: 'rgba(8,15,30,.58)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16 }} onClick={onClose}><div className="pm-card pm-fade-in" onClick={(e) => e.stopPropagation()} style={{ width: '100%', maxWidth: 620, maxHeight: '92vh', overflowY: 'auto', padding: 0 }}><div style={{ padding: 20, borderBottom: '1px solid var(--pm-border)', display: 'flex', alignItems: 'center', gap: 12 }}><div style={{ width: 42, height: 42, borderRadius: 10, background: 'var(--pm-primary-light)', color: 'var(--pm-primary)', display: 'grid', placeItems: 'center' }}><Icon size={20} /></div><div style={{ flex: 1 }}><div className="pm-section-title">{title}</div><div style={{ color: 'var(--pm-text-muted)', fontSize: '0.75rem' }}>{subtitle}</div></div><button className="pm-btn pm-btn-ghost pm-btn-sm" onClick={onClose}><X size={15} /></button></div><div style={{ padding: 20 }}>{children}</div>{footer && <div style={{ padding: '14px 20px', borderTop: '1px solid var(--pm-border)', display: 'flex', justifyContent: 'flex-end', gap: 8 }}>{footer}</div>}</div></div>;
}

function ExpenseModal({ expense, onClose }) {
  if (!expense) return null;
  const row = (label, value) => <div style={{ display: 'flex', justifyContent: 'space-between', gap: 14, padding: '10px 0', borderBottom: '1px solid var(--pm-border)', fontSize: '0.82rem' }}><span style={{ color: 'var(--pm-text-muted)' }}>{label}</span><strong style={{ textAlign: 'right' }}>{value}</strong></div>;
  return <Modal title={expense.id} subtitle="Expense / cost entry" icon={Receipt} onClose={onClose}>{row('Date', expense.date)}{row('Category', expense.category)}{row('Supplier', expense.supplier)}{row('Description', expense.description)}{row('Reference', expense.reference)}{row('Status', expense.status)}<div style={{ marginTop: 16, padding: 16, borderRadius: 10, background: 'var(--pm-surface-2)', border: '1px solid var(--pm-border)' }}><div style={{ fontSize: '0.72rem', color: 'var(--pm-text-muted)' }}>TOTAL COST</div><div style={{ fontFamily: "'Roboto Condensed', sans-serif", fontSize: '1.9rem', fontWeight: 700, marginTop: 3 }}>{money(expense.amount)}</div></div></Modal>;
}

function AddExpenseModal({ onClose, onCreated }) {
  const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), category: 'Medical consumables', supplier: '', description: '', amount: '', status: 'Pending', reference: '' });
  const [error, setError] = useState('');
  const set = (key) => (e) => setForm((prev) => ({ ...prev, [key]: e.target.value }));
  const submit = () => {
    if (!form.supplier.trim() || !form.description.trim() || Number(form.amount) <= 0) return setError('Supplier, description and a valid amount are required.');
    const result = createExpense(getFinanceData(), form);
    onCreated(result.data);
  };
  return <Modal title="Record Expense" subtitle="Add a hospital cost, supplier charge or operating expense" icon={Plus} onClose={onClose} footer={<><button className="pm-btn pm-btn-outline pm-btn-sm" onClick={onClose}>Cancel</button><button className="pm-btn pm-btn-primary pm-btn-sm" onClick={submit}><CheckCircle2 size={14} /> Save expense</button></>}>
    {error && <div style={{ padding: '10px 12px', borderRadius: 8, background: '#fee2e2', color: '#dc2626', fontSize: '0.8rem', marginBottom: 14 }}>{error}</div>}
    <div className="row g-3"><div className="col-md-6"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>Date</label><input type="date" value={form.date} onChange={set('date')} style={inputStyle} /></div><div className="col-md-6"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>Category</label><select value={form.category} onChange={set('category')} style={inputStyle}>{['Medical consumables','Pharmacy stock','Laboratory','Maintenance','Utilities','Staff costs','Transport','Facility operations','Other'].map((x) => <option key={x}>{x}</option>)}</select></div><div className="col-12"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>Supplier / payee</label><input value={form.supplier} onChange={set('supplier')} placeholder="Supplier or payee" style={inputStyle} /></div><div className="col-12"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>Description</label><input value={form.description} onChange={set('description')} placeholder="What was purchased or paid for?" style={inputStyle} /></div><div className="col-md-6"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>Amount (USD)</label><input type="number" min="0" step="0.01" value={form.amount} onChange={set('amount')} style={inputStyle} /></div><div className="col-md-6"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>Status</label><select value={form.status} onChange={set('status')} style={inputStyle}><option>Pending</option><option>Approved</option></select></div><div className="col-12"><label style={{ fontSize: '0.76rem', fontWeight: 700, marginBottom: 6, display: 'block' }}>PO / RFQ / reference</label><input value={form.reference} onChange={set('reference')} placeholder="Optional reference" style={inputStyle} /></div></div>
  </Modal>;
}

export default function AccountingPage() {
  const [data, setData] = useState(() => getFinanceData());
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const [selected, setSelected] = useState(null);
  const [adding, setAdding] = useState(false);

  const totals = useMemo(() => {
    const total = data.expenses.reduce((sum, item) => sum + Number(item.amount), 0);
    const approved = data.expenses.filter((item) => item.status === 'Approved').reduce((sum, item) => sum + Number(item.amount), 0);
    const pending = data.expenses.filter((item) => item.status === 'Pending').reduce((sum, item) => sum + Number(item.amount), 0);
    const revenue = data.invoices.reduce((sum, item) => sum + Number(item.paid), 0);
    return { total, approved, pending, revenue, operatingPosition: revenue - approved };
  }, [data]);

  const categoryTotals = useMemo(() => Object.entries(data.expenses.reduce((acc, item) => { acc[item.category] = (acc[item.category] || 0) + Number(item.amount); return acc; }, {})).sort((a,b) => b[1]-a[1]), [data.expenses]);
  const maxCategory = Math.max(...categoryTotals.map(([, value]) => value), 1);
  const filtered = data.expenses.filter((item) => {
    const q = query.toLowerCase().trim();
    return (!q || `${item.id} ${item.category} ${item.supplier} ${item.description} ${item.reference}`.toLowerCase().includes(q)) && (status === 'All' || item.status === status);
  });

  return <div>
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}><div style={{ width: 46, height: 46, borderRadius: 12, background: 'var(--pm-primary-light)', color: 'var(--pm-primary)', display: 'grid', placeItems: 'center' }}><Calculator size={23} /></div><div style={{ flex: 1 }}><h2 style={{ margin: 0, fontFamily: "'Roboto Condensed', sans-serif", fontSize: '1.35rem' }}>Accounting & Cost Control</h2><div style={{ fontSize: '0.8rem', color: 'var(--pm-text-muted)', marginTop: 3 }}>Operating expenses, supplier costs, approvals and cash position</div></div><button className="pm-btn pm-btn-primary pm-btn-sm" onClick={() => setAdding(true)}><Plus size={14} /> Record expense</button></div>

    <div className="row g-3 mb-4"><div className="col-6 col-xl-3"><div className="pm-stat-card"><div style={{ fontSize: '0.7rem', opacity: .8 }}>COLLECTED REVENUE</div><div style={{ fontSize: '1.8rem', fontWeight: 700, fontFamily: "'Roboto Condensed', sans-serif", marginTop: 5 }}>{money(totals.revenue)}</div><div style={{ fontSize: '0.7rem', opacity: .72, marginTop: 6 }}>Confirmed patient receipts</div></div></div><div className="col-6 col-xl-3"><div className="pm-stat-card" style={{ background: 'var(--pm-warning)' }}><div style={{ fontSize: '0.7rem', opacity: .8 }}>TOTAL COSTS</div><div style={{ fontSize: '1.8rem', fontWeight: 700, fontFamily: "'Roboto Condensed', sans-serif", marginTop: 5 }}>{money(totals.total)}</div><div style={{ fontSize: '0.7rem', opacity: .72, marginTop: 6 }}>{data.expenses.length} cost entries</div></div></div><div className="col-6 col-xl-3"><div className="pm-stat-card" style={{ background: 'var(--pm-info)' }}><div style={{ fontSize: '0.7rem', opacity: .8 }}>PENDING APPROVAL</div><div style={{ fontSize: '1.8rem', fontWeight: 700, fontFamily: "'Roboto Condensed', sans-serif", marginTop: 5 }}>{money(totals.pending)}</div><div style={{ fontSize: '0.7rem', opacity: .72, marginTop: 6 }}>{data.expenses.filter((e) => e.status === 'Pending').length} pending entries</div></div></div><div className="col-6 col-xl-3"><div className="pm-stat-card" style={{ background: totals.operatingPosition >= 0 ? 'var(--pm-success)' : 'var(--pm-danger)' }}><div style={{ fontSize: '0.7rem', opacity: .8 }}>CASH POSITION</div><div style={{ fontSize: '1.8rem', fontWeight: 700, fontFamily: "'Roboto Condensed', sans-serif", marginTop: 5 }}>{money(totals.operatingPosition)}</div><div style={{ fontSize: '0.7rem', opacity: .72, marginTop: 6 }}>Collections less approved costs</div></div></div></div>

    <div className="row g-3 mb-4"><div className="col-12 col-lg-5"><div className="pm-card h-100"><div className="pm-section-header"><div><div className="pm-section-title">Cost by category</div><div style={{ fontSize: '0.74rem', color: 'var(--pm-text-muted)' }}>Current ledger distribution</div></div><TrendingDown size={18} style={{ color: 'var(--pm-warning)' }} /></div>{categoryTotals.map(([category, value]) => <div key={category} style={{ marginBottom: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, fontSize: '0.78rem', marginBottom: 5 }}><span style={{ fontWeight: 600 }}>{category}</span><strong>{money(value)}</strong></div><div style={{ height: 7, background: 'var(--pm-border)', borderRadius: 20, overflow: 'hidden' }}><div style={{ width: `${(value / maxCategory) * 100}%`, height: '100%', background: 'var(--pm-primary)', borderRadius: 20 }} /></div></div>)}</div></div><div className="col-12 col-lg-7"><div className="pm-card h-100"><div className="pm-section-header"><div className="pm-section-title">Control summary</div><Landmark size={18} style={{ color: 'var(--pm-primary)' }} /></div><div className="row g-3"><div className="col-md-6"><div style={{ padding: 16, borderRadius: 10, background: 'var(--pm-surface-2)', border: '1px solid var(--pm-border)' }}><CheckCircle2 size={18} style={{ color: 'var(--pm-success)' }} /><div style={{ fontSize: '0.72rem', color: 'var(--pm-text-muted)', marginTop: 9 }}>APPROVED COSTS</div><div style={{ fontWeight: 700, fontSize: '1.25rem' }}>{money(totals.approved)}</div></div></div><div className="col-md-6"><div style={{ padding: 16, borderRadius: 10, background: 'var(--pm-surface-2)', border: '1px solid var(--pm-border)' }}><Clock size={18} style={{ color: 'var(--pm-warning)' }} /><div style={{ fontSize: '0.72rem', color: 'var(--pm-text-muted)', marginTop: 9 }}>AWAITING APPROVAL</div><div style={{ fontWeight: 700, fontSize: '1.25rem' }}>{money(totals.pending)}</div></div></div><div className="col-md-6"><div style={{ padding: 16, borderRadius: 10, background: 'var(--pm-surface-2)', border: '1px solid var(--pm-border)' }}><Building2 size={18} style={{ color: 'var(--pm-primary)' }} /><div style={{ fontSize: '0.72rem', color: 'var(--pm-text-muted)', marginTop: 9 }}>SUPPLIERS / PAYEES</div><div style={{ fontWeight: 700, fontSize: '1.25rem' }}>{new Set(data.expenses.map((e) => e.supplier)).size}</div></div></div><div className="col-md-6"><div style={{ padding: 16, borderRadius: 10, background: 'var(--pm-surface-2)', border: '1px solid var(--pm-border)' }}><ArrowUpRight size={18} style={{ color: totals.operatingPosition >= 0 ? 'var(--pm-success)' : 'var(--pm-danger)' }} /><div style={{ fontSize: '0.72rem', color: 'var(--pm-text-muted)', marginTop: 9 }}>OPERATING MARGIN</div><div style={{ fontWeight: 700, fontSize: '1.25rem' }}>{totals.revenue ? `${((totals.operatingPosition / totals.revenue) * 100).toFixed(1)}%` : '0.0%'}</div></div></div></div></div></div></div>

    <div className="pm-card"><div className="pm-section-header" style={{ flexWrap: 'wrap', gap: 10 }}><div><div className="pm-section-title">Expense ledger</div><div style={{ fontSize: '0.74rem', color: 'var(--pm-text-muted)' }}>Supplier invoices, operational costs and approvals</div></div><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><div style={{ position: 'relative' }}><Search size={14} style={{ position: 'absolute', left: 10, top: 9, color: 'var(--pm-text-muted)' }} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search expenses" style={{ ...inputStyle, paddingLeft: 31, width: 190, paddingTop: 7, paddingBottom: 7 }} /></div><select value={status} onChange={(e) => setStatus(e.target.value)} style={{ ...inputStyle, width: 'auto', paddingTop: 7, paddingBottom: 7 }}><option>All</option><option>Approved</option><option>Pending</option></select></div></div><div style={{ overflowX: 'auto' }}><table className="pm-table" style={{ minWidth: 760 }}><thead><tr><th>Date</th><th>Reference</th><th>Category</th><th>Supplier / payee</th><th>Status</th><th style={{ textAlign: 'right' }}>Amount</th><th></th></tr></thead><tbody>{filtered.map((expense) => <tr key={expense.id}><td>{expense.date}</td><td><strong>{expense.reference}</strong><div style={{ fontSize: '0.68rem', color: 'var(--pm-text-muted)' }}>{expense.id}</div></td><td>{expense.category}</td><td>{expense.supplier}</td><td><span className={`pm-badge ${expense.status === 'Approved' ? 'pm-badge-success' : 'pm-badge-warning'}`}>{expense.status}</span></td><td style={{ textAlign: 'right', fontWeight: 700 }}>{money(expense.amount)}</td><td style={{ textAlign: 'right' }}><button className="pm-btn pm-btn-ghost pm-btn-sm" onClick={() => setSelected(expense)}><Eye size={13} /> View</button></td></tr>)}</tbody></table></div></div>

    {selected && <ExpenseModal expense={selected} onClose={() => setSelected(null)} />}
    {adding && <AddExpenseModal onClose={() => setAdding(false)} onCreated={(next) => { setData(next); setAdding(false); }} />}
  </div>;
}
